SECRET_PATTERNS = {
    'AWS Access Key': (r'(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}', 'critical'),
    'AWS Secret Key': (r'(?i)aws[_\-\s]?secret[_\-\s]?(?:access)?[_\-\s]?key[\'"\s]*[:=][\'"\s]*([0-9a-zA-Z\/+]{40})', 'critical'),
    'AWS MWS Key': (r'amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', 'high'),
    'GitHub Token': (r'gh[pousr]_[0-9a-zA-Z]{36,}', 'critical'),
    'GitHub Classic': (r'ghp_[0-9a-zA-Z]{36,}', 'critical'),
    'GitHub OAuth': (r'gho_[0-9a-zA-Z]{36,}', 'critical'),
    'GitHub App': (r'(ghu|ghs)_[0-9a-zA-Z]{36,}', 'critical'),
    'GitHub Refresh': (r'ghr_[0-9a-zA-Z]{76,}', 'critical'),
    'GitLab Token': (r'glpat-[0-9a-zA-Z\-\_]{20,}', 'critical'),
    'GitLab Runner': (r'glrt-[0-9a-zA-Z\-\_]{20,}', 'high'),
    'Bitbucket Client ID': (r'(?i)bitbucket[_\-\s]?client[_\-\s]?id[\'"\s]*[:=][\'"\s]*([0-9a-zA-Z]{32})', 'high'),
    'Bitbucket Secret': (r'(?i)bitbucket[_\-\s]?secret[\'"\s]*[:=][\'"\s]*([0-9a-zA-Z]{64})', 'critical'),
    'Slack Token': (r'xox[baprs]-[0-9a-zA-Z\-]{10,72}', 'critical'),
    'Slack Webhook': (r'https://hooks\.slack\.com/services/T[a-zA-Z0-9_]+/B[a-zA-Z0-9_]+/[a-zA-Z0-9_]+', 'high'),
    'Stripe Live API': (r'sk_live_[0-9a-zA-Z]{24,}', 'critical'),
    'Stripe Test API': (r'sk_test_[0-9a-zA-Z]{24,}', 'medium'),
    'Stripe Restricted': (r'rk_live_[0-9a-zA-Z]{24,}', 'critical'),
    'Stripe Publishable': (r'pk_live_[0-9a-zA-Z]{24,}', 'low'),
    'PayPal Braintree': (r'access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}', 'critical'),
    'Square Access': (r'sq0atp-[0-9A-Za-z\-_]{22,}', 'critical'),
    'Square OAuth': (r'sq0csp-[0-9A-Za-z\-_]{43,}', 'critical'),
    'Google API Key': (r'AIza[0-9A-Za-z\-_]{35}', 'high'),
    'Google OAuth ID': (r'[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com', 'medium'),
    'Google OAuth Secret': (r'(?i)google[_\-\s]?(?:oauth)?[_\-\s]?secret[\'"\s]*[:=][\'"\s]*([0-9A-Za-z\-_]{24})', 'critical'),
    'Google Service Account': (r'"type":\s*"service_account"', 'critical'),
    'Firebase API': (r'(?i)firebase[_\-\s]?api[_\-\s]?key[\'"\s]*[:=][\'"\s]*([0-9A-Za-z\-_]{30,})', 'high'),
    'Azure Storage': (r'DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/=]{88,}', 'critical'),
    'Azure Client Secret': (r'(?i)azure[_\-\s]?client[_\-\s]?secret[\'"\s]*[:=][\'"\s]*([0-9A-Za-z\-_\.~]{34,})', 'critical'),
    'Heroku API': (r'[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}', 'medium'),
    'Mailgun API': (r'key-[0-9a-zA-Z]{32,}', 'high'),
    'MailChimp API': (r'[0-9a-f]{32}-us[0-9]{1,2}', 'high'),
    'Twilio API': (r'SK[0-9a-fA-F]{32}', 'critical'),
    'Twilio Account': (r'AC[0-9a-fA-F]{32}', 'medium'),
    'SendGrid API': (r'SG\.[0-9A-Za-z\-_]{22}\.[0-9A-Za-z\-_]{43}', 'critical'),
    'Telegram Bot': (r'[0-9]{8,10}:[A-Za-z0-9_-]{35}', 'high'),
    'Twitter Bearer': (r'A{22}[0-9A-Za-z%]{80,}', 'high'),
    'Twitter Access': (r'[0-9]{10,}-[0-9A-Za-z]{40}', 'high'),
    'Facebook Access': (r'EAACEdEose0cBA[0-9A-Za-z]+', 'critical'),
    'Facebook OAuth': (r'(?i)facebook[_\-\s]?(?:app)?[_\-\s]?secret[\'"\s]*[:=][\'"\s]*([0-9a-f]{32})', 'critical'),
    'NPM Token': (r'npm_[0-9a-zA-Z]{36,}', 'critical'),
    'Docker Hub': (r'dckr_pat_[0-9a-zA-Z_\-]{36,}', 'high'),
    'Cloudflare API': (r'(?i)cloudflare[_\-\s]?api[_\-\s]?key[\'"\s]*[:=][\'"\s]*([0-9a-f]{37})', 'high'),
    'DigitalOcean Token': (r'dop_v1_[0-9a-f]{64}', 'critical'),
    'DigitalOcean OAuth': (r'doo_v1_[0-9a-f]{64}', 'critical'),
    'Linode API': (r'(?i)linode[_\-\s]?token[\'"\s]*[:=][\'"\s]*([0-9a-f]{64})', 'high'),
    'CircleCI Token': (r'(?i)circle[_\-\s]?(?:ci)?[_\-\s]?token[\'"\s]*[:=][\'"\s]*([0-9a-f]{40})', 'high'),
    'Travis CI': (r'(?i)travis[_\-\s]?token[\'"\s]*[:=][\'"\s]*([0-9a-zA-Z]{22})', 'high'),
    'Codecov Token': (r'(?i)codecov[_\-\s]?token[\'"\s]*[:=][\'"\s]*([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})', 'medium'),
    'Sentry DSN': (r'https://[0-9a-f]{32}@[a-z0-9\-]+\.ingest\.sentry\.io/[0-9]+', 'medium'),
    'Datadog API': (r'(?i)datadog[_\-\s]?api[_\-\s]?key[\'"\s]*[:=][\'"\s]*([0-9a-f]{32})', 'high'),
    'New Relic License': (r'(?i)new[_\-\s]?relic[_\-\s]?license[_\-\s]?key[\'"\s]*[:=][\'"\s]*([0-9a-f]{40})', 'high'),
    'Algolia API': (r'(?i)algolia[_\-\s]?api[_\-\s]?key[\'"\s]*[:=][\'"\s]*([0-9a-f]{32})', 'medium'),
    'Mapbox Access': (r'pk\.[a-zA-Z0-9]{60,}', 'medium'),
    'Auth0 Client': (r'(?i)auth0[_\-\s]?client[_\-\s]?secret[\'"\s]*[:=][\'"\s]*([0-9A-Za-z\-_]{64})', 'critical'),
    'Okta Token': (r'(?i)okta[_\-\s]?token[\'"\s]*[:=][\'"\s]*([0-9a-zA-Z\-_]{42})', 'critical'),
    'JWT Token': (r'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}', 'low'),
    'SSH Private Key': (r'-----BEGIN (?:RSA|DSA|EC|OPENSSH) PRIVATE KEY-----', 'critical'),
    'PGP Private': (r'-----BEGIN PGP PRIVATE KEY BLOCK-----', 'critical'),
    'Generic Private Key': (r'-----BEGIN PRIVATE KEY-----', 'critical'),
    'Database URL MongoDB': (r'mongodb(?:\+srv)?://[^\s:]+:[^\s@]+@[^\s\/]+', 'critical'),
    'Database URL MySQL': (r'mysql://[^\s:]+:[^\s@]+@[^\s\/]+', 'critical'),
    'Database URL PostgreSQL': (r'postgres(?:ql)?://[^\s:]+:[^\s@]+@[^\s\/]+', 'critical'),
    'Database URL Redis': (r'redis://[^\s:]*:[^\s@]+@[^\s:]+:[0-9]+', 'critical'),
    'JDBC Connection': (r'jdbc:(?:mysql|postgresql|oracle|sqlserver)://[^\s]+', 'high'),
    'Connection String': (r'(?i)(?:Server|Data Source|Addr)=[^;]+;.*(?:Password|Pwd)=[^;]+', 'critical'),
    'API Key in URL': (r'[?&]api[_\-]?key=([a-zA-Z0-9]{16,})', 'high'),
    'Access Token in URL': (r'[?&]access[_\-]?token=([a-zA-Z0-9\-_\.]{20,})', 'high'),
    'Bearer in Auth': (r'Authorization:\s*Bearer\s+([a-zA-Z0-9\-_\.=]{20,})', 'high'),
    'Basic Auth': (r'Authorization:\s*Basic\s+([A-Za-z0-9+\/=]{20,})', 'high'),
    'Generic API Key': (r'(?i)api[_\-]?key[\'"\s]*[:=][\'"\s]*[\'"]?([0-9a-zA-Z\-_]{20,})[\'"]?', 'medium'),
    'Generic Secret': (r'(?i)(?:secret|password|passwd)[\'"\s]*[:=][\'"\s]*[\'"]?([^\s\'"]{12,})[\'"]?', 'medium'),
    'Generic Token': (r'(?i)token[\'"\s]*[:=][\'"\s]*[\'"]?([0-9a-zA-Z\-_\.]{20,})[\'"]?', 'medium'),
    'OAuth Client Secret': (r'(?i)client[_\-\s]?secret[\'"\s]*[:=][\'"\s]*[\'"]?([0-9a-zA-Z\-_]{20,})[\'"]?', 'high'),
    'Webhook URL': (r'https?://[^\s/]+/webhooks?/[^\s<>"\']+', 'medium'),
    'Private Token': (r'(?i)private[_\-\s]?token[\'"\s]*[:=][\'"\s]*([0-9a-zA-Z\-_]{20,})', 'high'),
    'Encryption Key': (r'(?i)encryption[_\-\s]?key[\'"\s]*[:=][\'"\s]*([0-9a-fA-F]{32,})', 'high'),
    'Master Key': (r'(?i)master[_\-\s]?key[\'"\s]*[:=][\'"\s]*([0-9a-zA-Z\-_+/=]{20,})', 'critical'),
    'PEM Certificate': (r'-----BEGIN CERTIFICATE-----', 'medium'),
    'Hex Secret 32+': (r'(?i)(?:secret|key|token|password)[\'"\s]*[:=][\'"\s]*[\'"]?([0-9a-fA-F]{32,})[\'"]?', 'medium'),
}

SKIP_EXTENSIONS = {
    '.jpg', '.jpeg', '.png', '.gif', '.bmp', '.ico', '.webp', '.svg',
    '.pdf', '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx',
    '.zip', '.tar', '.gz', '.bz2', '.7z', '.rar', '.tgz',
    '.exe', '.dll', '.so', '.dylib', '.bin',
    '.woff', '.woff2', '.ttf', '.eot', '.otf',
    '.mp3', '.mp4', '.avi', '.mov', '.wmv',
}

SKIP_DIRECTORIES = {
    'node_modules', 'venv', 'env', '__pycache__',
    '.venv', 'dist', 'build', '.next', 'target',
    'vendor', '.idea', '.vscode', 'coverage'
}
